version: '3'

services:
  app1:
    build:
      context: ./server1
    ports:
      - "80"

  app2:
    build:
      context: ./server2
    ports:
      - "80"

  nginx:
    image: nginx
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
